"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

import pygtk
pygtk.require('2.0')
import gtk
from cover_view_manager import CoverViewManager

class IconScrolledWindow(gtk.ScrolledWindow):
	def __init__(self):
		gtk.ScrolledWindow.__init__(self)

		self.set_policy(gtk.POLICY_AUTOMATIC, gtk.POLICY_AUTOMATIC)

		icon_view = gtk.IconView()
		icon_view.set_pixbuf_column(0)
		icon_view.set_text_column(1)
		icon_view.set_tooltip_column(2)
		icon_view.set_selection_mode(gtk.SELECTION_MULTIPLE)
		icon_view.set_item_width(194)
		icon_view.set_item_padding(5)

		CoverViewManager.set_icon_view(icon_view)

		self.add(icon_view)
