"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

import pygtk
pygtk.require('2.0')
import gtk

class MenuBar(gtk.MenuBar):
	def __init__(self, accel_group):
		gtk.MenuBar.__init__(self)

		file_menu = gtk.MenuItem("_File")
		file_menu_content = gtk.Menu()
		file_menu.set_submenu(file_menu_content)
		quit_menu_item = gtk.ImageMenuItem(gtk.STOCK_QUIT, accel_group)
		key_value, modifier = gtk.accelerator_parse("<Control>Q")
		quit_menu_item.add_accelerator("activate", accel_group, key_value, modifier, gtk.ACCEL_VISIBLE)
		quit_menu_item.connect("activate", gtk.main_quit)
		file_menu_content.append(quit_menu_item)
		self.append(file_menu)
