"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

import pynotify

class Notifier:
	@staticmethod
	def create_info_notification(title, body):
		Notifier.__create_notification(title, body, "dialog-info")

	def create_warning_notification(title, body):
		Notifier.__create_notification(title, body, "dialog-warning")

	def create_error_notification(title, body):
		Notifier.__create_notification(title, body, "dialog-error")

	@staticmethod
	def __create_notification(title, body, notification_type):
		pynotify.init("game-cataloger")
		notification = pynotify.Notification(title, body, notification_type)
		notification.set_urgency(pynotify.URGENCY_NORMAL)
		notification.set_timeout(pynotify.EXPIRES_DEFAULT)
		notification.show()
