"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

import pygtk
pygtk.require('2.0')
import gtk
from .. import gtkplus
from .. import util
from search_handler import SearchHandler
from update_database_handler import UpdateDatabaseHandler

class SearchBox(gtk.VBox):
	def __init__(self):
		gtk.VBox.__init__(self)

		tree_view = gtkplus.TreeView(util.TreeBuilder.build(True))

		column = gtk.TreeViewColumn()
		gtkplus.CellRendererToggle(column, tree_view, 0, 1)
		gtkplus.CellRendererText(column, 2)

		tree_view.append_column(column)
		tree_view.set_headers_visible(False)
		tree_scrolled_window = gtk.ScrolledWindow()
		tree_scrolled_window.set_policy(gtk.POLICY_AUTOMATIC, gtk.POLICY_AUTOMATIC)
		tree_scrolled_window.add_with_viewport(tree_view)

		search_entry = gtk.Entry()

		search_button = gtk.Button("Search")
		search_button.connect("clicked", SearchHandler.on_search_button_click, search_entry, tree_view, 0, 3)
		search_button.set_size_request(60, -1)

		search_box = gtk.HBox()
		search_box.pack_start(search_entry, True)
		search_box.pack_start(search_button, False)
		search_box.set_size_request(-1, 30)

		update_button = gtk.Button("Update Database")
		update_button.connect("clicked", UpdateDatabaseHandler.on_update_database_button_click, tree_view, 0, 3)
		update_button.set_size_request(-1, 30)

		self.pack_start(search_box, False)
		self.pack_start(tree_scrolled_window, True)
		self.pack_start(update_button, False)
		self.set_size_request(200, -1)
