"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

from folders_edit_adapter import *
from manufacturers_edit_adapter import *
from edit_adapter import *
