"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

from ... import sql
from edit_adapter import IEditAdapter
from manufacturers_edit_adapter import ManufacturersEditAdapter

class DevicesEditAdapter(IEditAdapter):
	def __init__(self):
		self._parent_adapter = ManufacturersEditAdapter()

	def get_items_parameters(self):
		return {"Name" : "text"}

	def get_items_list(self):
		list = []

		for item in sql.wrapper.Device.find_all():
			list.append([item.get_id(), str(item.get_name())])

		return list

	def get_items_list_by_parent(self, id):
		list = []

		for item in sql.wrapper.Device.find_all_by_foreign_key("manufacturer_id", sql.wrapper.Manufacturer.find_by_id(id)):
			list.append([item.get_id(), str(item.get_name())])

		return list

	def items_have_parent(self):
		return True

	def get_parent_type_name(self):
		return "Manufacturer"

	def get_items_parent_list(self):
		return self._parent_adapter.get_items_list()

	def get_item_parent(self, id):
		item = sql.wrapper.Device.find_by_id(id)

		return self._parent_adapter.get_item_values(item.get_parent().get_id())

	def get_item_values(self, id):
		item = sql.wrapper.Device.find_by_id(id)

		return {"id" : id, "Name" : item.get_name()}

	def save_item_values(self, id, parameters):
		item = sql.wrapper.Device.find_by_id(id) if id else sql.wrapper.Device()
		item.set_name(parameters["Name"])
		item.save(sql.wrapper.Manufacturer.find_by_id(parameters[self.get_parent_type_name()]), "manufacturer_id")

		return item
