"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

class IEditAdapter:
	def get_items_parameters(self):
		raise "Unimplemented Method!"

	def get_items_list(self):
		raise "Unimplemented Method!"

	def items_have_parent(self):
		raise "Unimplemented Method!"

	def get_items_parent_list(self):
		raise "Unimplemented Method!"

	def get_item_parent(self, id):
		raise "Unimplemented Method!"

	def get_item_values(self, id):
		raise "Unimplemented Method!"

	def save_item_values(self, id, parameters):
		raise "Unimplemented Method!"
