"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

from ... import sql
from edit_adapter import IEditAdapter

class FoldersEditAdapter(IEditAdapter):
	def get_items_parameters(self):
		return {"Alias" : "text", "Path" : "text"}

	def get_items_list(self):
		list = []

		for item in sql.wrapper.Folder.find_all():
			list.append([item.get_id(), str(item.get_alias()), str(item.get_path())])

		return list

	def items_have_parent(self):
		return False

	def get_item_values(self, id):
		item = sql.wrapper.Folder.find_by_id(id)
		return {"Alias" : item.get_alias(), "Path" : item.get_path()}

	def save_item_values(self, id, parameters):
		item = sql.wrapper.Folder.find_by_id(id) if id != None else sql.wrapper.Manufacturer()
		item.set_alias(parameters["Alias"])
		item.set_path(parameters["Path"])
		item.save()
