"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

from .. import gtkplus
from .. import sql

class TreeBuilder:
	@staticmethod
	def build(is_selected = False):
		k_tree = gtkplus.util.KTree([is_selected, False, "All", 0])

		for manufacturer in sql.wrapper.Manufacturer.find_all():
			k_tree.add_child(TreeBuilder.__parse_manufacturer(manufacturer, is_selected))

		return k_tree

	@staticmethod
	def __parse_manufacturer(manufacturer, is_selected):
		k_tree_node = gtkplus.util.KTree([is_selected, False, manufacturer.get_name(), manufacturer.get_id()])

		for device in sql.wrapper.Device.find_all_by_foreign_key("manufacturer_id", manufacturer):
			k_tree_node.add_child(TreeBuilder.__parse_device(device, is_selected))

		return k_tree_node

	@staticmethod
	def __parse_device(device, is_selected):
		k_tree_node = gtkplus.util.KTree([is_selected, False, device.get_name(), device.get_id()])

		for folder in sql.wrapper.Folder.find_all_by_foreign_key("device_id", device):
			k_tree_node.add_child(TreeBuilder.__parse_folder(folder, is_selected))

		return k_tree_node

	@staticmethod
	def __parse_folder(folder, is_selected):
		k_tree_node = gtkplus.util.KTree([is_selected, False, folder.get_alias(), folder.get_id()])

		return k_tree_node
