"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

class Configuration:
	def __init__(self):
		self._manufacturers = []

	def get_manufacturers(self):
		return self._manufacturers

	def add_manufacturer(self, manufacturer):
		self._manufacturers.append(manufacturer)
