"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

from .. import sql
from game_finder import GameFinder

class GameListUpdater:
	@staticmethod
	def update(folder):
		sql.wrapper.Game.save_all(GameFinder.find(folder), folder, "folder_id")
