"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

import os
from .. import sql

class GameFinder:
	@staticmethod
	def find(folder):
		games = []

		for file_name in sorted(os.listdir(os.path.normpath(folder.get_path()))):
			games.append(sql.wrapper.Game.create(file_name))

		return games
