"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

import sqlite3
import os

class ConnectionManager:
	_path = None
	_database = None

	@classmethod
	def setup(cls, path, database):
		cls._path = path
		cls._database = database

	@classmethod
	def get_connection(cls):
		connection = sqlite3.connect(os.path.join(cls._path, cls._database))
		connection.row_factory = sqlite3.Row

		return connection
