"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

class ApplicationWindowManager:
	_application_window = None

	@staticmethod
	def get_application_window():
		return ApplicationWindowManager._application_window

	@staticmethod
	def set_application_window(application_window):
		ApplicationWindowManager._application_window = application_window
