"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

from .. import sql
from cover_view_manager import CoverViewManager

class SearchHandler:
	@staticmethod
	def on_search_button_click(button, search_entry, tree_view, toggle_index, wrapper_index):

		model = tree_view.get_model()
		search_text = search_entry.get_text().replace("'", "''") + "%"
		CoverViewManager.update_view(SearchHandler.__handle_manufacturers(model.iter_children(model.get_iter("0")), model, toggle_index, wrapper_index, search_text))

	@staticmethod
	def __handle_manufacturers(iter, model, toggle_index, wrapper_index, search_text):
		manufacturers = []

		while iter is not None:
			if model[iter][toggle_index]:
				manufacturer = sql.wrapper.Manufacturer.find_by_id(model[iter][wrapper_index])
				manufacturer.add_devices(SearchHandler.__handle_devices(model.iter_children(iter), model, toggle_index, wrapper_index, search_text, manufacturer))
				manufacturers.append(manufacturer)

			iter = model.iter_next(iter)

		return manufacturers

	@staticmethod
	def __handle_devices(iter, model, toggle_index, wrapper_index, search_text, manufacturer):
		devices = []

		while iter is not None:
			if model[iter][toggle_index]:
				device = sql.wrapper.Device.find_by_id(model[iter][wrapper_index])
				device.add_folders(SearchHandler.__handle_folders(model.iter_children(iter), model, toggle_index, wrapper_index, search_text, device))
				devices.append(device)

			iter = model.iter_next(iter)

		return devices
	
	@staticmethod
	def __handle_folders(iter, model, toggle_index, wrapper_index, search_text, device):
		folders = []

		while iter is not None:
			if model[iter][toggle_index]:
				folder = sql.wrapper.Folder.find_by_id(model[iter][wrapper_index])
				folder.add_games(sql.wrapper.Game.find_all_where("name like '{0}' AND folder_id = {1}".format(search_text, folder.get_id()), "name"))
				folders.append(folder)

			iter = model.iter_next(iter)

		return folders
