"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

from . import Wrapper, Manufacturer

class Device(Wrapper):
	_table = "devices"
	_attributes_columns = {}
	_attributes_columns["_id"] = "id"
	_attributes_columns["_name"] = "name"
	_attributes_columns["_manufacturer_id"] = "manufacturer_id"

	@classmethod
	def find_by_name(cls, name):
		return cls.find_by_attribute("_name", name)

	def __init__(self, id = None, name = None):
		Wrapper.__init__(self, id)

		self._name = name
		self._folders = []
		self._manufacturer_id = 0

	def get_name(self):
		return self._name

	def get_folders(self):
		return self._folders

	def set_name(self, name):
		self._name = name

	def add_folder(self, folder):
		self._folders.append(folder)

	def add_folders(self, folders):
		self._folders.extend(folders)

	def _load_parent(self):
		self._parent = Manufacturer.find_by_id(self._manufacturer_id)
