"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

from . import Wrapper

class Manufacturer(Wrapper):
	_table = "manufacturers"
	_attributes_columns = {}
	_attributes_columns["_id"] = "id"
	_attributes_columns["_name"] = "name"

	@classmethod
	def find_by_name(cls, name):
		return cls.find_by_attribute("_name", name)

	def __init__(self, id = None, name = None):
		Wrapper.__init__(self, id)

		self._name = name
		self._devices = []

	def get_name(self):
		return self._name

	def get_devices(self):
		return self._devices

	def set_name(self, name):
		self._name = name

	def add_device(self, device):
		self._devices.append(device)

	def add_devices(self, devices):
		self._devices.extend(devices)

	def _load_parent(self):
		pass
